/*
 *  File_name:  bit_math.h
 *  Author:     Mohammed Hammad
 *  Date:       06/12/2023
 *  Version:    0.1
 */

#include "Timer0_interface.h"

void TIMER0_voidInit(void){
	#if TIMER0_MODE==TIMER0_NORMAL
		CLEAR_BIT(TCCR0,WGM00);
		CLEAR_BIT(TCCR0,WGM01);
	#elif TIMER0_MODE==TIMER0_CTC
		CLEAR_BIT(TCCR0,WGM00);
		SET_BIT(TCCR0,WGM01);
	#elif TIMER0_MODE==TIMER0_PWM
		SET_BIT(TCCR0,WGM00);
		SET_BIT(TCCR0,WGM01);
	#elif TIMER0_MODE==TIMER0_FASTPWM
		SET_BIT(TCCR0,WGM00);
		CLEAR_BIT(TCCR0,WGM01);
	#endif
	
	#if TIMER0_PRESCALER==TIMER0_STOP
		CLEAR_BIT(TCCR0,CS00);
		CLEAR_BIT(TCCR0,CS01);
		CLEAR_BIT(TCCR0,CS02);
	#elif TIMER0_PRESCALER==TIMER0_PRESCALING_1
		CLEAR_BIT(TCCR0,CS00);
		CLEAR_BIT(TCCR0,CS01);
		SET_BIT(TCCR0,CS02);
	#elif TIMER0_PRESCALER==TIMER0_PRESCALING_8
		CLEAR_BIT(TCCR0,CS00);
		SET_BIT(TCCR0,CS01);
		CLEAR_BIT(TCCR0,CS02);
	#elif TIMER0_PRESCALER==TIMER0_PRESCALING_64
		CLEAR_BIT(TCCR0,CS00);
		SET_BIT(TCCR0,CS01);
		SET_BIT(TCCR0,CS02);
	#elif TIMER0_PRESCALER==TIMER0_PRESCALING_256
		SET_BIT(TCCR0,CS00);
		CLEAR_BIT(TCCR0,CS01);
		CLEAR_BIT(TCCR0,CS02);
	#elif TIMER0_PRESCALER==TIMER0_PRESCALING_1024
		SET_BIT(TCCR0,CS00);
		CLEAR_BIT(TCCR0,CS01);
		SET_BIT(TCCR0,CS02);
	#elif TIMER0_u8_PRESCALER==TIMER0_EXTERNAL_FALLING
		SET_BIT(TCCR0,CS00);
		SET_BIT(TCCR0,CS01);
		CLEAR_BIT(TCCR0,CS02);
	#elif TIMER0_PRESCALER==TIMER0_EXTERNAL_RISING
		SET_BIT(TCCR0,CS00);
		SET_BIT(TCCR0,CS01);
		SET_BIT(TCCR0,CS02);
	#endif
	
	#if TIMER0_OC0==TIMER0_DISCONNECT
		CLEAR_BIT(TCCR0,COM00);
		CLEAR_BIT(TCCR0,COM01);
	#elif TIMER0_OC0==TIMER0_TOGGLE
		SET_BIT(TCCR0,COM00);
		CLEAR_BIT(TCCR0,COM01);
	#elif TIMER0_OC0==TIMER0_NONINVERTED||TIMER0_OC0==TIMER0_CLEAR
		CLEAR_BIT(TCCR0,COM00);
		SET_BIT(TCCR0,COM01);
	#elif TIMER0_OC0==TIMER0_INVERTED||TIMER0_OC0==TIMER0_SET
		SET_BIT(TCCR0,COM00);
		SET_BIT(TCCR0,COM01);
	#endif
}

void Timer0_OVInterrupt_Enable(void) {
    SET_BIT(TIMSK, TOIE0);
}

void Timer0_OVInterrupt_Disable(void) {
    CLEAR_BIT(TIMSK, TOIE0);
}

void Timer0_OCInterrupt_Enable(void) {
    SET_BIT(TIMSK, OCIE0);
}

void Timer0_OCInterrupt_Disable(void) {
    CLEAR_BIT(TIMSK, OCIE0);
}

void Timer0_FastPWM(u8 duty) {
	#if TIMER0_OC0==TIMER0_NONINVERTED
		OCR0 = ((TIMER0_REG_CAPACITY * duty) / 100) - 1;
	#elif TIMER0_OC0==TIMER0_INVERTED
		OCR0 = 255 - ((TIMER0_REG_CAPACITY * duty) / 100);
	#endif
}
void PWM_init(void) {
	SET_BIT(TCCR0, WGM00);
	SET_BIT(TCCR0, WGM01);
	SET_BIT(TCCR0, COM01);
	SET_BIT(TCCR0, CS00);
	DIO_Write_Pin_Dir(DIO_PORTB, PIN3, OUTPUT);
}
